### ISSUE TITLE
make fails 

### ISSUE THREAD

**Issue by akhst7** [timflutre/trimmomatic#1]
Hi, 

Trying to compile the 0.33 but fails with a following;

javac: file not found: /org/usadellab/trimmomatic/fasta/FastaParser.java

But FastaParser.java is there in the right path.  

My Mac:
ProductName:    Mac OS X
ProductVersion: 10.10.3
BuildVersion:   14D131

Java -version:
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

Thanks.

**Comment by timflutre** [comment]
As explained in the README, I am not the official maintainer of Trimmomatic. You should contact Anthony Bolger: http://www.usadellab.org/cms/index.php?page=trimmomatic

Moreover, I am not developing on Mac but GNU/Linux, and I have a very limited experience witj Java. So I managed to make it work on my machines, but have no idea why it is not working in yours. Good luck!
