### ISSUE TITLE
Web page down

### ISSUE THREAD

**Issue by weedcentipede** [timflutre/trimmomatic#13]
Hey, 
Your tutorial web page looks down,

Cheers, 
Luis Alfonso.

**Comment by timflutre** [comment]
As explained in the README, I am not the official maintainer of Trimmomatic (I also now prefer to use CutAdapt). For this issue, you should contact the original author, Anthony Bolger. Note also that I made this repo with version 0.33 of the code, but A. Bolger may have improved the code since.
