### ISSUE TITLE
The webpage with the manual has disappeared

### ISSUE THREAD

**Issue by NigelDyer** [timflutre/trimmomatic#15]
The webpage http://www.usadellab.org/cms/index.php?page=trimmomatic that provides the manual has disappeared.
Indeed, the whole domain has disappeared.  Could the manual be put onto github?

**Comment by mbhall88** [comment]
Until this is fixed you could use a web archive version of the manual at https://web.archive.org/web/20201201045428/http://www.usadellab.org/cms/index.php?page=trimmomatic

**Comment by greggles** [comment]
Looks like the page is back and I guess this could be closed.

**Comment by greggles** [comment]
I guess the official repository is now in Github as well at https://github.com/usadellab/Trimmomatic
