### ISSUE TITLE
trimmomatic-0.36 problem in managing threads

### ISSUE THREAD

**Issue by lmanchon** [timflutre/trimmomatic#3]
--Hi,

i have strange behaviour on my cluster node using trimmomatic regarding the use of multiple threads:

this is the command line i use:

java -XX:ParallelGCThreads=4 -XX:+DoEscapeAnalysis -Xmx8g -jar $prog/trimmomatic-0.36.jar PE -threads 16 -phred33 $IN_OUT/ERR532589_1.fastq.gz $IN_OUT/ERR532589_2.fastq.gz $IN_OUT/Out_ERR532589_1.fastq.gz $IN_OUT/Out_unpaired_ERR532589_1.fastq.gz $IN_OUT/Out_ERR532589_2.fastq.gz $IN_OUT/Out_unpaired_ERR532589_2.fastq.gz ILLUMINACLIP:$ADAPTERS/TruSeq3-PE-2.fa:2:40:15:8:true LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36

it was mentionned that i use 16 threads but in the log file of my LSF job i see only 4 processes:

Resource usage summary:

```
CPU time :               20157.96 sec.
Max Memory :             3544 MB
Average Memory :         2677.95 MB
Total Requested Memory : 124800.00 MB
Delta Memory :           121256.00 MB
(Delta: the difference between Total Requested Memory and Max Memory.)
Max Processes :          4
Max Threads :            51
```

What is the best way to optimize my command line, it seems that if i put 4,6..or 16 theads the behaviour and the elapsed time still the same.

I work on node with 2 CPU (8 core each) and 128GB per node

thank you,
Laurent --

**Comment by timflutre** [comment]
As explained in the README, I am not the official maintainer of Trimmomatic (I also now prefer to use [CutAdapt](http://cutadapt.readthedocs.io/en/stable/)). For this issue, you should contact Anthony Bolger (http://www.usadellab.org/cms/index.php?page=trimmomatic). Note also that I made this repo with version 0.33 of the code, but I can see that it is now at version 0.36.
